# Generated by Django 5.2.15 on 2026-07-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prayerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
